apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "vol1-pv"
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/srv/nfs/vol1"
    server: "oselab.example.com"